### PR TITLE
!food: Only hilight users who are on channel

### LINKED ISSUE #21: !food: Only highlight online users

### PR DESCRIPTION
**Pull request by nicoonoclaste**
Closes #21.

Please test before deploying, I'm not sure how to test r3bot without running a complete copy of it and connecting it to our channel.

### CODE REVIEW

**Comment by PeterTheOne** [comment]
You could write a unit test for it!

**Comment by stefan2904** [comment]
yolo

**Comment by stefan2904** [comment]
Simple testa failing hard! https://travis-ci.org/realraum/r3bot-irc/builds/121176488

Yo Mr @nbraud, how do you do boolean operations in Python? :P

**Comment by nicoonoclaste** [comment]
@PeterTheOne Nope.  There is no documentation on how to make tests for this thing  ;-)

@stefan2904 No, I'm not a Python dev.
Also, the arguments to `filter` were in the wrong order, but Mr. @stefan2904 didn't catch that  :P

**Pull request closed without merging**
